### ISSUE TITLE
Retain cycle when trying to disconnect

### ISSUE THREAD

**Issue by slice** [pusher/NWWebSocket#33] opened 2021-11-14 12:25 UTC
I'm trying to call `NWWebSocket.disconnect()` in my app, but the WebSocket never appears to actually get closed. 

If I pull up a memory graph, there's a retain cycle:

<img width="625" alt="image" src="https://user-images.githubusercontent.com/4206232/141680768-09e9eee9-7799-431e-bf3b-c0be71298d5b.png">

Xcode says that a strong capture in the closure in `NWWebSocket.scheduleDisconnectionReporting` is retaining the object:

```swift
    private func scheduleDisconnectionReporting(closeCode: NWProtocolWebSocket.CloseCode,
                                                reason: Data?) {
        // Cancel any existing `disconnectionWorkItem` that was set first
        disconnectionWorkItem?.cancel()

        disconnectionWorkItem = DispatchWorkItem {
            self.delegate?.webSocketDidDisconnect(connection: self,
                                                  closeCode: closeCode,
                                                  reason: reason)
        }
    }
```

The `webSocketDidDisconnect` delegate method does get called (with a close code of `1001`), but the WebSocket stays connected.

**Comment by benjamin-tang-pusher** [comment] 2021-11-18 22:54
Hi, I couldn't spot a retain cycle in my app after calling disconnect:

![Screenshot 2021-11-18 at 17 46 14](https://user-images.githubusercontent.com/83954069/142508854-a4a2d4e0-1354-4b8f-9de7-c3ef1b750565.png)

I don't see a the purple exclamation on my NWWebSocket, although please correct me if I'm missing something.

If I'm not, I'd like to see more of your code if possible.

**Comment by slice** [comment] 2021-11-19 12:23
Sure thing. I was using NWWebSocket in my code [here].(https://github.com/slice/basilisk/blob/317dc9209760ec5ccbdceec5ecb348fe125408eb/Contempt/Gateway/GatewayConnection.swift#L61)

Since you can't seem to reproduce the retain cycle, I'm going to assume that I was doing something incorrectly, and Xcode was unable to display the root problem in my code via the memory graph. Feel free to close this issue in that case.

**Comment by slice** [comment] 2022-07-07 04:09
[A bit later...]

![image](https://user-images.githubusercontent.com/4206232/177688560-8810a318-6731-4801-aacd-0b2c1b004e30.png)

Looks like this could be relevant. Not sure if the issue is resolved in the betas; I don't install them on my Macs and I'm no longer using NWWebSocket. But I just thought I'd bring this up.

**Comment by benjamin-tang-pusher** [comment] 2022-10-18 09:01
Thanks for that.

I will close this, since this can't be reproduced.

**Closed by benjamin-tang-pusher** 2022-10-18 09:01 UTC
